# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{git-svn-mirror}
  s.version = "0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eloy Duran"]
  s.date = %q{2010-10-11}
  s.default_executable = %q{git-svn-mirror}
  s.description = %q{A command-line tool that automates the task of creating a GIT mirror for a SVN repo, and keeping it up-to-date.}
  s.email = %q{eloy.de.enige@gmail.com}
  s.executables = ["git-svn-mirror"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md",
     "TODO"
  ]
  s.files = [
    "LICENSE",
     "README.md",
     "TODO",
     "bin/git-svn-mirror",
     "git-svn-mirror.gemspec",
     "lib/git-svn-mirror.rb"
  ]
  s.homepage = %q{http://github.com/alloy/git-svn-mirror}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A command-line tool that automates the task of creating a GIT mirror for a SVN repo, and keeping it up-to-date.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

